### ISSUE TITLE
Implement responsive design of main menu

### ISSUE THREAD

**Issue by marekyggdrasil** [Grinnode-live/grinnode-live-frontend#10]
It would be good to fix the menu on mobile browsers.

Desktop:

![screencapture-grinnode-live-2020-11-26-11_19_41](https://user-images.githubusercontent.com/8202674/100304337-7c045700-2fd9-11eb-9881-5a71ddaa1f25.png)

Mobile:

![screencapture-grinnode-live-2020-11-26-11_20_37](https://user-images.githubusercontent.com/8202674/100304346-81fa3800-2fd9-11eb-810f-4c1a873b34b3.png)

**Comment by MCM-Mike** [comment]
@stakervali can we close this?

**Comment by stakervali** [comment]
Yes, please close the issue.
