### ISSUE TITLE
Links to FAQ sections - add anchors (html?) 

### ISSUE THREAD

**Issue by MCM-Mike** [Grinnode-live/grinnode-live-frontend#27]
We should make it easy to link to some FAQs on our https://grinnode.live/faq site. 

**Example:**
How can we link to:`What is Grin?` and send the link to a user to just click on it and share it.
https://grinnode.live/faq#whatisgrin

**Comment by stakervali** [comment]
Will add a link button for easy sharing.

**Comment by MCM-Mike** [comment]
any progress here ?

**Comment by stakervali** [comment]
This is implemented and ready to be published with next update.

![resim](https://user-images.githubusercontent.com/60194710/120483977-49d61680-c3bb-11eb-890a-a7001bdb2897.png)

**Comment by MCM-Mike** [comment]
> This is implemented and ready to be published with next update.
> 
> ![resim](https://user-images.githubusercontent.com/60194710/120483977-49d61680-c3bb-11eb-890a-a7001bdb2897.png)

ok, once you tested it please create a PR .
