### ISSUE TITLE
add grin emmisions to stat page

### ISSUE THREAD

**Issue by stakervali** [Grinnode-live/grinnode-live-frontend#28]
add grin emmisions from grinexplorer.net
start date when grin launched in jan 2019

**Comment by MCM-Mike** [comment]
any progress here , or do you need any further help ?

**Comment by stakervali** [comment]
I have just finished grin address check and working on this now. I am planning to add it today via querying owner_api to both frontend and grinnode.live public api.

**Comment by stakervali** [comment]
Added emmission to stat page. Since we have already querying blockheight in frontend, I converted it into grin. I added thousand decimal seperators for better readability. @MCM-Mike should we add `emission` as a backend api point?

![resim](https://user-images.githubusercontent.com/60194710/120482799-26f73280-c3ba-11eb-8f88-0e9a3da097d6.png)
