### ISSUE TITLE
Page load is slow due to loading full material icon set

### ISSUE THREAD

**Issue by stakervali** [Grinnode-live/grinnode-live-frontend#40]
Site has a low page speed (57/100 by google pagespeed insights). One of the reasons for slowness is loading of full material icon set. Picking only necessary ones will result a faster site for visitors.

**Comment by MCM-Mike** [comment]
thank you for reporting it, can you also fix it within the new upgrade we planning?

**Comment by stakervali** [comment]
Yes, I plan to fix it before upgrade.

**Comment by stakervali** [comment]
Improved mobile pagespeed to 60/100. Closing the issue.
