### ISSUE TITLE
Grin++ Nodes announcement

### ISSUE THREAD

**Issue by MCM-Mike** [Grinnode-live/grinnode-live-frontend#52]
Announcement: 
We are running three (3) Grin-PlusPlus nodes, 2 in Europe and one in the US. 

GrinPP nodes:
(by Grinnode.live)

grinpp01 | Europe | 1 Gbit |
grinpp02 | Europe | 1 Gbit | 
grinpp03 | USA      |  1 Gbit | 

We need to find a place on the site where we can add these 3 nodes as an announcement.

**Comment by stakervali** [comment]
I think best place is the home screen. I have added another banner, is this make it too crowded?

![image](https://user-images.githubusercontent.com/60194710/150096492-1a50d2db-c7a3-4892-ab09-67ac1bd9784c.png)

**Comment by MCM-Mike** [comment]
I suggest putting it under:

```
Updates
08/2021
API endpoint for block height
We have added a new endpoint for block height of grin chain and current emission. There may be a latency for up to 30 minutes, like all other endpoints, there is a timestamp field in the api response.

``` 

Somewhere here should be enough.

**Comment by stakervali** [comment]
Added the update, PR here [grinplusplus_update](https://github.com/Grinnode-live/grinnode-live-frontend/pull/53)

![image](https://user-images.githubusercontent.com/60194710/150410218-0f3c0dfd-0d4c-4bf3-a57a-2149c8925294.png)

**Comment by MCM-Mike** [comment]
Can we close this now?

**Comment by stakervali** [comment]
Added to frontend, closing the issue...
