### ISSUE TITLE
Graph types (txcounts)

### ISSUE THREAD

**Issue by davidtavarez** [Grinnode-live/grinnode-live-frontend#59]
Probably different types of graphs could help to see the data easily. Something like this:
![Screenshot 2022-02-07 095635](https://user-images.githubusercontent.com/337107/152756422-9cf02fc6-a679-4dd4-956a-90f52b298350.png)
![Screenshot 2022-02-07 095648](https://user-images.githubusercontent.com/337107/152756428-f94fbd25-68e5-4cd9-a452-cd82b16e3f8c.png)

**Comment by stakervali** [comment]
At the moment we are using Scatter+line chart when there are few points. When number of points are high, line charts could be demanding on  low-spec mobile devices. We can add an option for bar type under the chart.

**Comment by stakervali** [comment]
Added bar type option in development branch.
![image](https://user-images.githubusercontent.com/60194710/166108204-b3a8642a-d464-456d-ac19-3757bea28182.png)

**Comment by stakervali** [comment]
Added with [af92142](https://github.com/Grinnode-live/grinnode-live-frontend/commit/af92142090e030f78426f126f1f47c2a76a0c94c), closing...
