### ISSUE TITLE
if grin had the Market cap of ..?

### ISSUE THREAD

**Issue by mojitoo** [Grinnode-live/grinnode-live-frontend#61]
People often thinks that linear emission is an issue and that it will only makes the price go down. what they are missing is that the problem is demand and not a monetary policy on itself.

So my idea is to have a chart, that will show grin price on a giving day, if grin market cap was equal to Btc market cap on that same day. 

we can of course decline the idea and have multiple charts for xmr, eth etc

the idea is inspired from https://www.marketcapof.com/grin/bitcoin.

**Comment by MCM-Mike** [comment]
Thank you for your idea.
Would this be possible to make @stakervali ?

**Comment by stakervali** [comment]
@mojitoo thanks for sharing the idea! 
@MCM-Mike, yes, it is possible. We can store daily data in backend or make multiple queries from frontend without involving backend. But certainly doable. 
People are usually concerned about emmission in the future would a negative effect, Maybe we can make a projection to the future, calculating the price with predefined emmission ratios.

**Comment by MCM-Mike** [comment]
> @MCM-Mike, yes, it is possible.

Would you work with @mojitoo in this issue to try to map out a development road-map and then align with me when we start working on it and the amount of time is needed?

**Comment by stakervali** [comment]
> Would you work with @mojitoo in this issue to try to map out a development road-map and then align with me when we start working on it and the amount of time is needed?

Sure! 

@mojitoo, what is your username in the forum, can you shoot me a DM to discuss this issue further?

**Comment by mojitoo** [comment]
thank you
i sent you a message on the forum

**Comment by stakervali** [comment]
Added with [af92142](https://github.com/Grinnode-live/grinnode-live-frontend/commit/af92142090e030f78426f126f1f47c2a76a0c94c), closing...
