### ISSUE TITLE
upgrade node-forge to version 1.3.0 or later.

### ISSUE THREAD

**Issue by MCM-Mike** [Grinnode-live/grinnode-live-frontend#67]
Dependabot is creating a security update to fix [6 Dependabot alerts](https://github.com/Grinnode-live/grinnode-live-frontend/security/dependabot?q=is%3Aopen+package%3Anode-forge+manifest%3Apackage-lock.json+has%3Apatch) on node-forge in [package-lock.json](https://github.com/Grinnode-live/grinnode-live-frontend/blob/-/package-lock.json).

Or, manually upgrade node-forge to version 1.3.0 or later. For example:

**Impact**
RSA PKCS#1 v1.5 signature verification code is lenient in checking the digest algorithm structure. This can allow a crafted structure that steals padding bytes and uses unchecked portion of the PKCS#1 encoded message to forge a signature when a low public exponent is being used.

**Patches**
The issue has been addressed in node-forge 1.3.0.

**References**
For more information, please see
["Bleichenbacher's RSA signature forgery based on implementation error"](https://mailarchive.ietf.org/arch/msg/openpgp/5rnE9ZRN1AokBVj3VqblGlP63QE/)
by Hal Finney.

For more information
If you have any questions or comments about this advisory:

Open an issue in [forge](https://github.com/digitalbazaar/forge)

**Comment by stakervali** [comment]
Updated with #71, closing the issue.
